// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rest

import (
	"waterforcast/pkg/domain/forcast/cmds"
	"waterforcast/pkg/infra/repos"
)

// Injectors from wire.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func InitializeRestApp() (*RestApp, error) {
	forcastRepository := repos.NewForcastRepository()
	addForcastHandler := cmds.NewAddForcastHandler(forcastRepository)
	restApp := NewRestApp(addForcastHandler)
	return restApp, nil
}
