// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"main.go/pkg/domains"
	"main.go/pkg/domains/beer"
	"main.go/pkg/domains/financial"
	"main.go/pkg/domains/room"
)

// Injectors from wire.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func InitializeApp() (*app, error) {
	beerDomain := beer.NewBeerDomain()
	financialDomain := financial.NewFinancialDomain()
	roomDomain := room.NewRoomDomain()
	domain := domains.NewDomain(beerDomain, financialDomain, roomDomain)
	appApp := newApp(domain)
	return appApp, nil
}
